spring:
  application:
    name: ai_projects
  datasource:
    url: jdbc:postgresql://localhost:5433/ai_projects_db
    username: rtb
    password: rtb_temp_12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

ai:
  api:
    key: ${GEMINI_API_KEY}
server:
  port: 7070

allowedOrigins: http://localhost:4200  # frontend host url
