apiVersion: v1
kind: Service
metadata:
  name: ai-backend-service
  namespace: ai-projects
spec:
  selector:
    app: ai-backend
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
      nodePort: 30007
  type: NodePort