apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-db-deployment
  namespace: ai-projects
  labels:
    app: ai-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-db
  template:
    metadata:
      labels:
        app: ai-db
    spec:
      containers:
      - name: ai-db
        image: ai-db:v1.0.0
        ports:
          - containerPort: 5432
        envFrom:
          - configMapRef:
              name: ai-backend-config
          - secretRef:
              name: ai-backend-secret
        volumeMounts:
          - name: db-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: ai-db-pvc
